"""Persistence port consumed by Nemo Server application services."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from nemo.core.contracts.types import Event, Message, RunResult, RunStatus

TERMINAL_STATUSES = frozenset(
    {
        RunStatus.COMPLETED.value,
        RunStatus.FAILED.value,
        RunStatus.CANCELLED.value,
        RunStatus.INTERRUPTED.value,
        RunStatus.LIMIT_REACHED.value,
    }
)


class Repository(Protocol):
    def close(self) -> None: ...
    def create_session(
        self, *, session_id: str, workspace: Path, model: str | None,
        approval_mode: str, user_instructions: str | None,
        project_instructions: str | None,
    ) -> dict[str, Any]: ...
    def get_session(self, session_id: str) -> dict[str, Any] | None: ...
    def list_sessions(self) -> list[dict[str, Any]]: ...
    def delete_session(self, session_id: str) -> None: ...
    def update_session(
        self, session_id: str, *, model: str | None = None,
        approval_mode: str | None = None,
    ) -> dict[str, Any] | None: ...
    def messages(self, session_id: str) -> tuple[Message, ...]: ...
    def create_run(
        self, *, run_id: str, session_id: str, prompt: str, max_steps: int,
    ) -> dict[str, Any]: ...
    def get_run(self, run_id: str) -> dict[str, Any] | None: ...
    def list_runs(self, session_id: str) -> list[dict[str, Any]]: ...
    def set_run_model(
        self, run_id: str, *, selection: str, model_name: str, model_id: str,
        protocol: str, provider: str,
    ) -> None: ...
    def set_run_running(self, run_id: str) -> None: ...
    def finish_run(self, result: RunResult, *, terminal_event: Event) -> None: ...
    def fail_run(self, run_id: str, message: str) -> None: ...
    def interrupt_run(self, run_id: str) -> None: ...
    def append_event(
        self, *, run_id: str, step: int, kind: str,
        payload: dict[str, Any], timestamp: str | None = None,
    ) -> Event: ...
    def append_runtime_event(self, event: Event) -> Event: ...
    def events_after(self, run_id: str, seq: int = 0) -> list[Event]: ...
    def steps(self, run_id: str) -> list[dict[str, Any]]: ...
    def tool_calls(self, run_id: str) -> list[dict[str, Any]]: ...
    def create_approval(
        self, *, request_id: str, run_id: str, tool_name: str,
        summary: str, reason: str, step: int,
    ) -> None: ...
    def answer_approval(self, request_id: str, outcome: str) -> bool: ...
    def get_approval(self, request_id: str) -> dict[str, Any] | None: ...
    def recover_interrupted_runs(self) -> list[str]: ...
    def request_cancel(self, run_id: str) -> None: ...
    def cancel_requested(self, run_id: str) -> bool: ...
    def owns_run(self, run_id: str) -> bool: ...
